# Generated by Django 5.1 on 2024-09-04 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP inválido. O formato deve ser 12345-678 ou 12345678.', regex='^\\d{5}-?\\d{3}$')])),
                ('rua', models.CharField(max_length=40)),
                ('numero', models.CharField(blank=True, max_length=6, null=True)),
                ('departamentos', models.ManyToManyField(related_name='predios', to='departamento.departamento')),
            ],
        ),
    ]
