# Generated by Django 5.1 on 2024-09-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('universidade', models.CharField(choices=[('ufrpe', 'UFRPE'), ('ufpe', 'UFPE')], max_length=100)),
                ('area', models.CharField(choices=[('exatas', 'Ciências Exatas'), ('humanas', 'Ciências Humanas'), ('biologicas', 'Ciências Biológicas'), ('sociais', 'Ciências Sociais Aplicadas'), ('artes', 'Artes e Design'), ('saude', 'Ciências da Saúde'), ('letras', 'Letras'), ('agrarias', 'Ciências Agrárias')], max_length=100)),
                ('coordenador', models.CharField(max_length=100)),
            ],
        ),
    ]
