# Generated by Django 5.1 on 2024-09-04 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nascimento', models.DateField()),
                ('tipo', models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
