# Generated by Django 5.1 on 2024-09-04 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Em análise', 'Em análise'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], max_length=100)),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamento', to='sala.sala')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
