# Generated by Django 5.1 on 2024-09-04 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('predio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descricao', models.CharField(max_length=300)),
                ('qtd_cadeiras', models.IntegerField()),
                ('andar', models.IntegerField()),
                ('tipo', models.CharField(choices=[('sala', 'Sala'), ('desenho', 'Sala de Desenho'), ('lab', 'Laboratório'), ('auditorio', 'Auditório')], max_length=100)),
                ('id_predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sala', to='predio.predio')),
            ],
        ),
    ]
